# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jisu Kim (Kevin)
title: Machine Learning Engineer
email: king9701@naver.com
# email_title: Email (Email title override)
phone: +82)1036928203
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
github_username:  Kevin-JisuKim
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: j1sssss0o
linkedin_username: jisu-kim-1293b3204
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  My name is Jisu Kim and I'm a machine learning software engineer and researcher.

  I'm interested in overall machine learning engineering, including computer vision and nlp.
  
  My particular interest in how to collect and refine data to create meaningful machine learning data and how to design a network effectively.

  [Here](./assets/Portfolio_Kevin_Jisu_Kim.pdf) is my development portfolio.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Lomin
        caption: Oct. 2023 ~ present
        description: | # this will include new lines to allow paragraphs
          **Development of a model running on an edge device**

          *(Jun. 2024 ~ present)*

          - Develop a model to understand images collected from a car navigation camera and extract the necessary information
          - Lightweight the model to run on a constrained-performance edge device(TX2 board)
          - ***Client***: Hyundai AutoEver
          - ***Keyword***: Quantization, Edge AI

          ---

          **Development of a model understanding financial documents**

          *(May. 2024 ~ Jul. 2024)*

          - Develop a model to understand financial documents and extract the necessary information
          - Design a process that can simplify various postprocessing steps
          - ***Client***: Mirae Asset Securities

          ---

          **Development of a model understanding medical documents**

          *(Feb. 2024 ~ May. 2024)*

          - Develop a model to understand medical documents and extract the necessary information
          - Develop a model specialized in extracting tabular data
          - ***Client***: KB Insurance, Hyundai Marine & Fire Insurance, Lotte Non-Life Insurance
      
          ---

          **Development of zero-shot document understanding prototype model**

          *(Jan. 2024 ~ Feb. 2024)*

          - Develop a multi-modal model capable of understanding diverse documents without learning specific to individual documents
          - ***Keyword***: Zero-shot learning

          ---
          
          **Development of a stamp area detection model for documents**

          *(Nov. 2023 ~ Jan. 2024)*

          - Develop a model to detect stamped areas on documents and automatically extract the content of the stamps
          - ***Client***: Korean Intellectual Property Office(KIPO)

          ---

          **Development of a model for detecting problem areas and inferring problem types in workbooks**
          
          *(Oct. 2023 ~ Nov. 2023)*
          
          - Develop a model to disaggregate the multiple problems within a workbook into individual entities and infer the types of each problem
          - Ultimately convert all problems within the workbook into individual datasets
          - ***Client***: Visang Education

      - layout: left
        border: weak
        title: Archidraw
        caption: Mar. 2022 ~ Oct. 2023
        description: | # this will include new lines to allow paragraphs
          **Development of automatic data processing for product recommendation service**

          *(Sep. 2023 ~ Oct. 2023)*

          - Design processes that automatically learn and update a model with products updated daily(100% automatic)
          - ***Keyword***: AutoML, Airflow

          ---
          
          **Development of AI Interior service with diffusion**

          *(Jul. 2023 ~ Aug. 2023)*

          - Develop a service that can change the interior style based on the user's render shot
          - ***Keyword***: Stable Diffusion

          ---

          **Development of a model that separates rooms with complex structures into meaningful areas**
          
          *(Apr. 2023 ~ Apr. 2023)*
          
          - Develop of a model to separate big rooms combined into one space to meaningful subrooms, such as living rooms, kitchens, and dining rooms
          
          ---

          **Research on generative AI**
          
          *(Mar. 2023 ~ Oct. 2023)*
          
          - Research on the various methods with a diffusion technique that can be used for floorplan images, render shots, etc.

          ---

          **Development of render shot score measurement model and designing an automated learning process**
          
          *(Dec. 2022 ~ Feb. 2023)*
          
          - Develop and upgrade a model that scores the quality of render shots
          - Design a process that automatically learn and update a model with user feedback(100% automatic)
          - ***Keyword***: AutoML, Airflow
          
          ---

          **Development of furniture location recommendation model**
          
          *(Oct. 2022 ~ Nov. 2022)*
          
          - Develop a model that recommends the appropriate location of the furniture selected by the user in consideration of the room structure and the location of the arranged furniture

          ---

          **Development of automatic dimension line recognition function of floorplan images**
          
          *(Jul. 2022 ~ Sep. 2022)*
          
          - Develop a model automatically recognizes the dimension lines contained in the floorplan images to read the dimension values
          - Automate a process about uploading floorplan images in Archisketch service
          - ***Keyword***: Image Processing
          
          ---

          **Development of product recommendation service**
          
          *(Jun. 2022 ~ Jul. 2022)*
          
          - Develop a service that analyzes the association of furniture used together within the Archisketch project and recommends furniture that would be good to place with the furniture selected by the user
          - ***Keyword***: Recommendation System

          ---

          **Development of recommendation service for render shot location**
          
          *(May. 2022 ~ Jun. 2022)*
          
          - Develop a service that analyzes the structure of the room selected by the user and recommends a location where a good render shot can be taken

          ---

          **Development of a model that classifies a room type**
          
          *(Mar. 2022 ~ May. 2022)*
          
          - Develop a model for inferring the room type of a render shot generated on the Archisketch platform

      - layout: left
        title: Plug N Play
        caption: Oct. 2021 ~ Feb. 2022
        description: | # this will include new lines to allow paragraphs
          **Project leading and development about PLUK**

          *(Oct. 2021 ~ Feb. 2022)*

          - Develop an artist-friendly platform called "PLUK" that analyzes the sound sources of the market through its own algorithm to learn the characteristics and performance of the sound source, predicts the performance of the new sound source, and provides a guide to composition
          - [**Article about PLUK**](https://www.news1.kr/articles/?4595881)

  - title: Career
    layout: list
    content:
      - layout: right
        border: weak
        title: Lomin
        sub_title: Machine learning research engineer
        caption: Oct. 2023 ~ present
        description: | # this will include new lines to allow paragraphs
          - Machine learning research engineer conducting research on document understanding
          - Conduct multi-modal research to comprehend various documents visually and contextually
          - Model optimization and lightweighting for model inference in diverse environments
          - Development was mainly carried out using python, and model construction was carried out using and pytorch

      - layout: right
        border: weak
        title: Archidraw
        sub_title: Machine learning software engineer
        caption: Mar. 2022 ~ Oct. 2023
        description: | # this will include new lines to allow paragraphs
          - Machine learning software engineer responsible for overall development of artificial intelligence-related features provided by 3D interior solution archisketch
          - Provide artificial intelligence services by organizing and learning various models by collecting data from various services, including editors and dashboards provided by Archisketch, and refining the data to suit the necessary functions to be utilized
          - Development of capabilities that automate internal data processing and processing to help process tasks in-house
          - Help users use services by automating difficult tasks such as furniture placement or preprocessing for drawing image recognition
          - Development was mainly carried out using python, and model construction was carried out using tensorflow and pytorch
      
      - layout: right
        title: Plug N Play
        sub_title: A one-man developer
        caption: Oct. 2021 ~ Feb. 2022
        description: | # this will include new lines to allow paragraphs
          - Responsible for data collection and refinement, model construction and implementation, and the creation and distribution of alpha version service pages, as a one-man developer of AI project PLUK

  - title: Education
    layout: list
    content:
      - layout: left
        border: weak
        title: Hanyang University
        sub_title: M.S. in Computer Science
        caption: Mar. 2020 ~ Feb. 2022
        description: | # this will include new lines to allow paragraphs
          - **Department of Computer Science**
          - **Thesis**
            - Sudden sensorineural hearing loss(SSNHL) prognosis prediction with ensemble and contrastive learning
            - Restore from Restored: Single-image Inpainting
          - **Advisor**
            - [*Tae Hyun Kim*](https://sites.google.com/view/lliger9/team/taehyunkim)
          - **GPA**
            - 3.98 / 4.5
      
      - layout: left
        title: Hanyang University
        sub_title: B.S. in Organic and Nano Engineering
        caption: Mar. 2015 ~ Feb. 2020
        description: | # this will include new lines to allow paragraphs
          - **Department of Organic and Nano Engineering**
          - **Thesis**
            - Production of magnesium cobalt oxide-based supercapacitor and capacity improvement by adding cationic and anionic surfactant
          - **Advisor**
            - [*Hee Joon Ahn*](https://sites.google.com/view/surfacesciencelab/people/professor)
          - **GPA**
            - 3.64 / 4.5

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
